[window]
padding = { x = 4, y = 4 }
decorations = "None"
opacity = 0.98                     
blur = false
startup_mode = "Maximized"
title = "My Terminal"
decorations_theme_variant = "Dark"
resize_increments = false
level = "Normal"
