[colors]
cursor = { text = "#ffffff", cursor = "#00f7ff" }

[colors.primary]
background = "#0c0e14"       # hitam kebiruan, seperti bayangan es malam
foreground = "#e0f2ff"       # putih kebiruan, sangat sejuk

[colors.normal]
black   = "#0c0e14"
red     = "#ff4f69"          # pink kemerahan, kayak neon hangat
green   = "#4ae38a"          # hijau mint dingin
yellow  = "#f4e06d"          # kuning sejuk, tidak menyilaukan
blue    = "#4caeff"          # biru glacier
magenta = "#c59fff"          # ungu pastel yang dreamy
cyan    = "#00f7ff"          # neon cyan super segar
white   = "#e0f2ff"

[colors.bright]
black   = "#1f2129"
red     = "#ff7b94"
green   = "#84f2b5"
yellow  = "#fff29e"
blue    = "#8bc9ff"
magenta = "#dfc2ff"
cyan    = "#87ffff"
white   = "#f1faff"
