[colors]
cursor = {text = "#1e2124", cursor = "#5ef1ff"}

[colors.primary]
background = "#16181a"
foreground = "#ffffff"

[colors.normal]
white = "#ffffff"
black = "#3c4048"
blue = "#5ea1ff"
green = "#5eff6c"
cyan = "#5ef1ff"
red = "#ff6e5e"
magenta = "#ff5ef1"
yellow = "#f1ff5e"

[colors.bright]
white = "#ffffff"
black = "#3c4048"
blue = "#5ea1ff"
green = "#5eff6c"
cyan = "#5ef1ff"
red = "#ff6e5e"
magenta = "#ff5ef1"
yellow = "#f1ff5e"
