[colors]
cursor = { text = "#e6f0ff", cursor = "#4cc9f0" }

[colors.primary]
background = "#0a0f1a"   # biru gelap kehitaman, bagus dengan transparency
foreground = "#e6f0ff"   # biru pucat/putih kebiruan

[colors.normal]
black   = "#0a0f1a"
red     = "#ff6b6b"       # merah pastel sedikit soft
green   = "#22c55e"       # hijau segar modern
yellow  = "#facc15"       # kuning neon-ish tapi tidak silau
blue    = "#3b78ff"       # biru utama (dipertahankan dari milikmu)
magenta = "#c084fc"       # ungu modern, tidak terlalu neon
cyan    = "#22d3ee"       # cyan lembut modern
white   = "#e6f0ff"

[colors.bright]
black   = "#1e293b"
red     = "#ff8787"
green   = "#4ade80"
yellow  = "#fde68a"
blue    = "#60a5fa"
magenta = "#d8b4fe"
cyan    = "#67e8f9"
white   = "#f1f5f9"
