[colors]
cursor = { text = "#00ff5f", cursor = "#00ff5f" }

[colors.primary]
background = "#000000"       # hitam total — seolah kamu di ruangan gelap
foreground = "#00ff5f"       # hijau fosfor terang — khas hacking gear

[colors.normal]
black   = "#000000"
red     = "#ff005f"          # merah darah menyala
green   = "#00ff5f"          # hijau fosfor
yellow  = "#b6e000"          # kuning kehijauan (hacker-style)
blue    = "#0087ff"          # biru tajam
magenta = "#af5fff"          # ungu hacker misterius
cyan    = "#00ffd7"          # cyan neon
white   = "#d0d0d0"          # abu terang

[colors.bright]
black   = "#505050"
red     = "#ff5f87"
green   = "#5fffaf"
yellow  = "#d7ff5f"
blue    = "#5fafff"
magenta = "#d7afff"
cyan    = "#87ffff"
white   = "#ffffff"
