[colors]
cursor = { text = "#1e222a", cursor = "#89dceb" }

[colors.primary]
background = "#1e222a"         
foreground = "#d8dee9"         

[colors.normal]
black   = "#3b4252"            
red     = "#ec6b64"            
green   = "#a6e3a1"            
yellow  = "#f9e2af"            
blue    = "#89b4fa"            
magenta = "#cba6f7"            
cyan    = "#89dceb"            
white   = "#e5e9f0"            

[colors.bright]
black   = "#4c566a"
red     = "#f38ba8"
green   = "#b5f4bc"
yellow  = "#fae3b0"
blue    = "#a3cbe7"
magenta = "#ddbdfd"
cyan    = "#b3f1f7"
white   = "#ffffff"

